<?php if (isset($user) && $user): ?>
    <?php require 'templates/layout/header.phtml'; ?>
<?php endif; ?>

<ul class="list-group">
<?php foreach($tasks as $task) : ?>
    <li class="list-group-item item-task <?php if ($task->finalizada) echo 'finished'; ?>">
        <div class="label">
            <b><?= htmlspecialchars($task->titulo) ?></b> | (Prioridad <?= htmlspecialchars($task->prioridad) ?>)
          <!--ver mas para que cuando este logueado muestre el nombre-->
          <?php if (isset($user) && $user): ?>
            <a class="btn btn-sm" href="verMasLogin/<?= htmlspecialchars($task->id) ?>">Ver más</a>
            <?php else : ?>
                 <a class="btn btn-sm" href="verMas/<?= htmlspecialchars($task->id) ?>">Ver más</a>
            <?php endif; ?>
        </div>


        <!-- Solo mostrar las acciones si el usuario está autenticado -->
        <?php if (isset($user) && $user): ?>
        <div class="actions">
            <?php if (!$task->finalizada): ?>
                <a href="finalizar/<?= $task->id ?>" class="btn btn-sm btn-success ml-auto">FINALIZAR</a>
            <?php endif ?>
            <a class="btn btn-sm btn-primary" href="modificar/<?= $task->id ?>">MODIFICAR</a>
            <a class="btn btn-sm btn-danger" href="eliminar/<?= $task->id ?>">ELIMINAR</a>
        </div> 
        <?php endif; ?>
    </li>
<?php endforeach ?>
</ul>
<?php if (isset($user) && $user): ?>
    <a class="btn btn-primary mt-2" href="nueva">Agregar</a>
    <?php endif; ?>

<p class="mt-3"><small>Mostrando <?= count($tasks) ?> tareas</small></p>

<?php require 'templates/layout/footer.phtml' ?>